apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: WorkflowAutomationTestQA/python-hello-world-QA/.cloudbees/workflows/callable-workflow-82ee377f-3e23-4d76-99d5-ae092f93f192.yaml
    