apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: WorkflowAutomationTestQA/python-hello-world-QA/.cloudbees/workflows/callable-workflow-151fec78-8719-43f9-bfd8-be241284f6a1.yaml
    