apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: WorkflowAutomationTestQA/python-hello-world-QA/.cloudbees/workflows/callable-workflow-ac0636ce-4061-4785-bab1-d58d9348e1ad.yaml
    