apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: WorkflowAutomationTestQA/python-hello-world-QA/.cloudbees/workflows/callable-workflow-d7191ac7-e0fe-4dab-8b79-5c2c2f654921.yaml
    